version: "3.8"

services:

  # ===================================================
  # Serviço: Backend Node.js (usa Mongo remoto)
  # ===================================================
backend:
  build:
    context: ./dropshipping-backend
    dockerfile: Dockerfile
  env_file:
    - ./dropshipping-backend/.env
  ports:
    - "5001:5001"
  command: ["npm", "start"]
  restart: unless-stopped

  # ===================================================
  # Serviço: Frontend React + Nginx
  # ===================================================
  frontend:
    container_name: dropshipping-frontend
    build:
      context: ./dropshipping-frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: "http://backend:5001/api"
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
