version: "3.8"

services:

  # ===================================================
  # Serviço: MongoDB
  # ===================================================
  mongo:
    image: mongo:6.0-alpine
    container_name: dropshipping-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  # ===================================================
  # Serviço: Backend Node.js
  # ===================================================
  backend:
    container_name: dropshipping-backend
    build:
      context: ./dropshipping-backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./dropshipping-backend/.env
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    volumes:
      - ./dropshipping-backend:/app
      # Se não quiser volume em produção, remova a linha acima.
    command: ["npm", "run", "dev"] 
    # Caso seu backend não tenha nodemon, altere para ["npm","start"]

  # ===================================================
  # Serviço: Frontend React + Nginx
  # ===================================================
  frontend:
    container_name: dropshipping-frontend
    build:
      context: ./dropshipping-frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongodb_data:
